-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 08:17:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SpotiHome
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SpotiHome` ;

-- -----------------------------------------------------
-- Schema SpotiHome
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpotiHome` DEFAULT CHARACTER SET utf8 ;
USE `SpotiHome` ;

-- -----------------------------------------------------
-- Table `SpotiHome`.`Music`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotiHome`.`Music` ;

CREATE TABLE IF NOT EXISTS `SpotiHome`.`Music` (
  `ID_Music` INT NOT NULL AUTO_INCREMENT,
  `name_Music` VARCHAR(255) CHARACTER SET 'utf16' COLLATE 'utf16_general_ci' NOT NULL,
  `dateDl_Music` TIMESTAMP NOT NULL,
  `duration_Music` TIME NULL,
  `title_Music` VARCHAR(255) CHARACTER SET 'utf16' COLLATE 'utf16_general_ci' NULL,
  `uploader_Music` VARCHAR(255) CHARACTER SET 'utf16' COLLATE 'utf16_general_ci' NULL,
  `linkYoutube_Music` VARCHAR(255) NULL,
  `linkSpotify_Music` VARCHAR(255) NULL,
  `linkDeezer_Music` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_Music`),
  UNIQUE INDEX `ID_Music_UNIQUE` (`ID_Music` ASC) VISIBLE,
  UNIQUE INDEX `name_Music_UNIQUE` (`name_Music` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotiHome`.`Playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotiHome`.`Playlist` ;

CREATE TABLE IF NOT EXISTS `SpotiHome`.`Playlist` (
  `ID_Playlist` INT NOT NULL AUTO_INCREMENT,
  `name_Playlist` VARCHAR(255) NULL,
  PRIMARY KEY (`ID_Playlist`),
  UNIQUE INDEX `ID_Playlist_UNIQUE` (`ID_Playlist` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotiHome`.`Rel_PlaMus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotiHome`.`Rel_PlaMus` ;

CREATE TABLE IF NOT EXISTS `SpotiHome`.`Rel_PlaMus` (
  `ID_Rel_PlaMus` INT NOT NULL AUTO_INCREMENT,
  `FK_Music` INT NULL,
  `FK_Playlist` INT NULL,
  `dateAdded_Rel_PlaMus` TIMESTAMP NULL,
  PRIMARY KEY (`ID_Rel_PlaMus`),
  UNIQUE INDEX `ID_Rel_PlaMus_UNIQUE` (`ID_Rel_PlaMus` ASC) VISIBLE,
  INDEX `FK_Music_idx` (`FK_Music` ASC) VISIBLE,
  INDEX `FK_Playlist_idx` (`FK_Playlist` ASC) VISIBLE,
  CONSTRAINT `FK_Music_PlaMus`
    FOREIGN KEY (`FK_Music`)
    REFERENCES `SpotiHome`.`Music` (`ID_Music`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Playlist_PlaMus`
    FOREIGN KEY (`FK_Playlist`)
    REFERENCES `SpotiHome`.`Playlist` (`ID_Playlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotiHome`.`Format`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotiHome`.`Format` ;

CREATE TABLE IF NOT EXISTS `SpotiHome`.`Format` (
  `ID_Format` INT NOT NULL AUTO_INCREMENT,
  `name_Format` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Format`),
  UNIQUE INDEX `ID_Format_UNIQUE` (`ID_Format` ASC) VISIBLE,
  UNIQUE INDEX `name_Format_UNIQUE` (`name_Format` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotiHome`.`Rel_ForMus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpotiHome`.`Rel_ForMus` ;

CREATE TABLE IF NOT EXISTS `SpotiHome`.`Rel_ForMus` (
  `ID_Rel_ForMus` INT NOT NULL AUTO_INCREMENT,
  `FK_Music` INT NULL,
  `FK_Format` INT NULL,
  PRIMARY KEY (`ID_Rel_ForMus`),
  UNIQUE INDEX `ID_Rel_ForMus_UNIQUE` (`ID_Rel_ForMus` ASC) VISIBLE,
  INDEX `FK_Music_idx` (`FK_Music` ASC) VISIBLE,
  INDEX `FK_Format_idx` (`FK_Format` ASC) VISIBLE,
  CONSTRAINT `FK_Music_ForMus`
    FOREIGN KEY (`FK_Music`)
    REFERENCES `SpotiHome`.`Music` (`ID_Music`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Format_ForMus`
    FOREIGN KEY (`FK_Format`)
    REFERENCES `SpotiHome`.`Format` (`ID_Format`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
